package lk.ijse.vimukthi.util;

public enum Routes {
    ADMIN , EMPLOYEE , DASHBOARD , REGISTER , MANAGEEMPLOYEE , MANAGECUSTOMER , MANAGESUPPLIER , MANAGEITEM, INCOMEREPORT, PLACEORDER, MANAGEUSER
}
